# Generated by Django 3.2.5 on 2022-02-20 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=200)),
                ('content', models.CharField(default='No content', max_length=1000)),
                ('level', models.CharField(choices=[('A1', 'Beginner1'), ('A2', 'Beginner2'), ('B1', 'Intermediate1'), ('B2', 'Intermediate2'), ('C1', 'Advanced1'), ('C2', 'Advanced2')], default='A1', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(default='', max_length=200)),
                ('word_meaning', models.CharField(default='', max_length=200)),
                ('word_note', models.CharField(default='', max_length=200)),
                ('word_tag', models.CharField(default='', max_length=200)),
                ('familiarity', models.CharField(choices=[('1', 'New'), ('2', 'Seen'), ('3', 'Familiar'), ('4', 'Known')], default='1', max_length=254)),
                ('last_review', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languagelessons.word')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=200)),
                ('familiar_words', models.PositiveIntegerField(default=1)),
                ('lessons_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languagelessons.lesson')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languagelessons.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateTimeField(auto_now_add=True)),
                ('listening_time', models.PositiveIntegerField()),
                ('words_read', models.PositiveIntegerField()),
                ('known_words', models.PositiveIntegerField()),
                ('familiar_words', models.PositiveIntegerField()),
                ('words_reviewed', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languagelessons.profile')),
            ],
        ),
    ]
