# Generated by Django 3.2.5 on 2022-02-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='words_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='languagelessons.word'),
        ),
    ]
