# Generated by Django 3.2.5 on 2022-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0002_alter_profile_words_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.CharField(default='No content', max_length=2200),
        ),
    ]
