# Generated by Django 3.2.5 on 2022-02-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0003_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
