# Generated by Django 3.2.5 on 2022-07-16 07:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0004_lesson_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default='lesson01.m4a', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\dougl\\projects\\bulmaluxembourgish\\media'), upload_to='media'),
        ),
    ]
