# Generated by Django 4.1 on 2022-08-05 09:04

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0006_auto_20220717_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default='lesson01.m4a', storage=django.core.files.storage.FileSystemStorage(location='/home/douglas/Public/bulmaluxembourgish/media'), upload_to='media'),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.URLField(default='')),
                ('words_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languagelessons.word')),
            ],
        ),
    ]
