# Generated by Django 3.2.5 on 2022-08-06 08:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0007_alter_lesson_audio_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.CharField(default='No content', max_length=3000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default='lesson01.m4a', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\dougl\\projects\\bulmaluxembourgish\\media'), upload_to='media'),
        ),
    ]
