# Generated by Django 3.2.5 on 2022-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0008_auto_20220806_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_timestamps',
            field=models.CharField(default='No content', max_length=3000),
        ),
    ]
