# Generated by Django 4.1 on 2022-08-19 08:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0009_lesson_content_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='content_lu',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_fr',
            field=models.CharField(default='No content', max_length=3000),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_pt',
            field=models.CharField(default='No content', max_length=3000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default='lesson01.m4a', storage=django.core.files.storage.FileSystemStorage(location='/home/douglas/Public/bulmaluxembourgish/media'), upload_to='media'),
        ),
    ]
