# Generated by Django 4.0 on 2022-08-20 09:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0010_rename_content_lesson_content_lu_lesson_content_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(default='lesson01.m4a', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\dougl\\projects\\bulmaluxembourgish\\media'), upload_to='media'),
        ),
    ]
