# Generated by Django 4.0 on 2022-08-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0011_alter_lesson_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='translation_preference',
            field=models.CharField(choices=[('Portugese', 'Portugese'), ('English', 'English'), ('French', 'French')], default='English', max_length=254),
        ),
    ]
