# Generated by Django 3.2.5 on 2022-08-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0012_profile_translation_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_note',
            new_name='meaning_reference',
        ),
        migrations.RemoveField(
            model_name='word',
            name='familiarity',
        ),
        migrations.RemoveField(
            model_name='word',
            name='last_review',
        ),
    ]
