# Generated by Django 3.2.5 on 2022-08-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagelessons', '0013_auto_20220821_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_meaning',
            new_name='word_en_meaning',
        ),
        migrations.AddField(
            model_name='word',
            name='word_fr_meaning',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='word',
            name='word_pt_meaning',
            field=models.CharField(default='', max_length=200),
        ),
    ]
